meta(charset:"utf-8") newLine()
meta(name:"viewport", content:"width=device-width, initial-scale=1.0") newLine()
title("${config.blog_title}") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/asciidoctor.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/prettify.css") newLine()
newLine()