language: groovy

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.gradle"

script:
  - "./gradlew clean bake convertCSS"

deploy:
  provider: s3
  access_key_id: AKIAIUE4KXBVJORVA3SA
  secret_access_key:
    secure: omeuxyZm1p5qCyj1j2Aydm0sppk/AezZpW3FHre0PJpI7lVWHUyPk6qNqx76ZP6Ef4elHw+si82tyzjYAWzjzhGBQ+Xb3S4GkOChujnhjwFRtAEHgxEep6lE89HGXh92SyOzAWZ+ixrZ3APAyD8qi/MKY8tMTCaQO2YVJu74Nsd4k3/tb0EYUiseeImUCEnFdhHSC73Uppst3pcVJCCQvDdXGgyxOmLhbW4i5u4fa8CDGqKLjtgZC7wcF6Dy4DRlILX7AXKMv7L1Ndb0rf8BSx51+rpTFDcRaBsC59yD6ydUgIXeWIBW1qTJ2CX5UkHOtaVfFSoBjkq1voZpojbjl773KBNP4m/eGSp3ymT+dXGZcqdqJtoaCQzvem8AIIsZ80Mj6ww58OeBxCPtHxedyuU8mE0nYtd0nCkD5qmyGWBrjkozU3PNAIjtvRHO1Srt3X99g/p3XN9b33bzUfzTGDcNuXjtt+twsFSkUahIOgU01j33+97hZucpccXuJEbxh8cNIhWfKkZ4XvoWvwEA/R7LycoVRlNY0rVkygmd9UulgVe4VtJ9YAwZJ4Y477SK7hFnLfsMbtRTnZkMm2W1hdXXoNFsl0yC1CX5LwN1XGHj8Brzk78xkBHMYpYKBviT9+mOFB81kMjyFKuEfKEATTMl41fE7qwEbO/HsnKntKU=git
  bucket: groovy-baking
  region: Bucket region
  upload-dir: groovy-baking
