language: groovy
jdk:
- oraclejdk8
os:
- linux
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean bake convertCSS"
deploy:
  provider: s3
  access_key_id: AKIAI4BXXYI5UPA6X4AA
  secret_access_key:
    secure: SvaFghPijF3+qGr7lQ/BQ1Sr8XQwGCwZX1yTuAt/2L6leJ1gaome0Ao4vLwPlJV2MIS8xsNaCjKWrOclBuypYWEBZf2P4TssWYNpOSJShZZ+HbkJF56hN3oq8YFX0GlGsIq4WrajnM9et/wdSXBCp2s+INHLlU8CgdvTNiiN2s4ubV/o8ZkX1ySmkuIKGiiNzEPkLl5iB0L5YyKjb/Dew7g/LDCnSukTbH1WS8Dtsaa/TFzk3ygm6hcSg0HU90pJveO0YiHSuBJXUR1Dj471KiVRCRuiWpdg8mz5pWTzASaOVT8JB+p9s7N4b89FauBoFdd7WumYQzL4/ABb7e8aGOmlwlb3yV8MbvK7JsAzQfFqQFlvRXpZhzDkihXTD3LmPhjj11aXv3c+eyuKEOJ0Vhpn1reYuXMr9gquJ1q4zjeWKxjxugRQ9KZO7RL0yF/5H60Kp7nIoXQ8GDJmpOkCcjt5ZipnQRprQXOmj5DGYC1HrPkcg8Nvj5LGbYhRobjDVX3U/Rc9muIUxDVkkMhFcAE1pwrY1pfRuZrg1vmFh5iBW5G3Bpn2pkwAhQ5rLFjYgcSpY+k5h05YuIWAIFRLzPyIw1x4vXlthjAIvgHXNF291gqEaPeIRmjaQcvQTtSfuq37Ny9AiO8yqz56SzVB/GYJhfKZbvyh+g12B1U3ayA=
  bucket: groovy-baking
  local-dir: "$TRAVIS_BUILD_DIR/build/jbake"
