language: groovy
jdk:
- oraclejdk8
os:
- linux
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean bake convertCSS"
deploy:
  provider: s3
  access_key_id: AKIAI4BXXYI5UPA6X4AA
  secret_access_key:
    secure: bjhB6lkygXeSXYkdOE7nMtXGtXw9aCDhBOzvZP/CPDAAw4NrvBooAzhyAS9YnDdLngePlVKJY+KPblLPuotN3QiDJhoTav9mk+Z3nzfHftjgGUAobyuscXm4jZe8Eiycvu9Pg/tmy9egBeM+3CHFjuzgB/DUh/xGB48ElRblITfuDMlIv74u+if+gDn9DU8Nryl4HbinmBrheClWtCVi//+4giKd+DUH4OmVqmdqjFZMWlilh5++m06vLaabMq1SGW/s/Qi3rnDWyYSEwBqRUYrUxS6sHfA5OS5nyjjMlPsMzVdga0X5V61yfhjvpBuBXaimaZEWKj/4KGHeoChhKD5rGtYdFeG6NlRVo7Yv+3llPqmK1oBevlVGgMc8ZSo9T1K+uBtJBVJp5vO1883+Gv9wVu7pJiMTh/5rKqb+a/rmnFsIwneBKeFx4217R3ErLKZa0Png+IwRZE64k+wWTi93/59RmS2nGetjmyHScQKTfTKa8nauXWPQHKYtfwDzPRdnGbVj+CyQ+VtPblmHEhOxEII52K3+lNdGRUnYU/5saLUWz25OytABcp6uX0ABTgJn1BrTYQMfiX/sNcISfZj2645R86LEQXQatpO3BPAHT+Ha6tG//mFVYSlaIZQA2/rbSkn0XcLxAlzekSpNaeeB/sDjBjjCTDA3Iex1Frs=
  bucket: groovy-baking
  upload-dir: build/jbake
